services:
  backend:
    container_name: fastifyBackend
    build: ./
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - PORT=${PORT}
      - HOST=${HOST}
      - HASHING_SECRET=${HASHING_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_TEMP_PW=${GOOGLE_TEMP_PW}
    restart: always

# docker compose --env-file ./backend/.env up