services:
  # Frontend Service Configuration
  frontend:
    build: 
      context: ./frontend
      # Use new Dockerfile that supports rootless mode and security requirements
      dockerfile: Dockerfile
      no_cache: true
    ports:
      # Dynamic port mapping with fallback to 3000
      # FRONTEND_PORT can be changed without modifying this file
      - "3000:3000"
    # Ensure container restarts unless explicitly stopped
    # This improves reliability in production
    restart: unless-stopped
    environment:
      # Production mode for better performance and security
      - NODE_ENV=development
      - API_URL=http://backend:3001
    init: true
    tty: true
    stdin_open: true
    command: sh -c "npm run start"  # Add ls command to see files
    depends_on:
      - backend

  # Backend Service Configuration
  backend:
    build:
      context: ./backend/srcs
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/data:/usr/src/app/data
    init: true
    tty: true
    stdin_open: true

