# Removed version for compatibility

x-compose-remove-orphans: true

services:
  # Backend Service Configuration (now includes frontend build)
  backend: # Renamed service to 'app' or keep 'backend' - let's keep 'backend' for consistency with Makefile
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
    init: true # Kept for now, might be removable
    user: "root" # Kept for now, might be removable

# Removed frontend service

# Removed networks section as it's not explicitly used

# Removed volumes section as it's not explicitly used
