version: '3.8'

services:
  # Frontend Service Configuration
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:4002
    init: true
    user: root

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "4002:4002"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    init: true
    user: root

  # Pong Standalone Service
  pongstandalone:
    build:
      context: ./pongstandalone-tomerge
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "4001:4001"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    init: true
    user: root

volumes:
  backend_data:

