services:
  # Frontend Service Configuration
  frontend:
    build: 
      context: .  # Changed to root context to access tests
      dockerfile: ./frontend/Dockerfile
      no_cache: true
    ports:
      # Dynamic port mapping with fallback to 3000
      # FRONTEND_PORT can be changed without modifying this file
      - "3000:3000"
    # Ensure container restarts unless explicitly stopped
    # This improves reliability in production
    restart: unless-stopped
    environment:
      # Production mode for better performance and security
      - NODE_ENV=development
      - API_URL=http://backend:3001
    # Removed volume mounts
    init: true
    tty: true
    stdin_open: true
    command: sh -c "npm run start"  # Add ls command to see files
    depends_on:
      - backend

  # Backend Service Configuration
  backend:
    build:
      context: .  # Changed to root context to access tests
      dockerfile: ./backend/srcs/Dockerfile
      no_cache: true
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    # Removed volume mounts
    init: true
    tty: true
    stdin_open: true

